package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Dec 16 10:06:30 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName( value ="auth_access" )
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class AuthAccess{



   	@TableId(value = "id",type = IdType.AUTO)
	private Long id;

	/**
	 * 角色code
	 */
   	@TableField(value = "role_code" )
	private String roleCode;

	/**
	 * 访问路径
	 */
   	@TableField(value = "access_url" )
	private String accessUrl;

	/**
	 * 描述
	 */
   	@TableField(value = "describes" )
	private String describes;

   	@TableLogic(value = "0",delval = "1")
   	@TableField(value = "is_del",select = false)
	private Integer isDel;

}
