package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Dec 16 10:06:36 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName( value ="role" )
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Role  {



    @TableId(value = "id",type = IdType.AUTO)
	private Long id;

	/**
	 * 角色code
	 */
   	@TableField(value = "role_code" )
	private String roleCode;

	/**
	 * 角色名
	 */
   	@TableField(value = "role_name" )
	private String roleName;

   	@TableLogic(value = "0",delval = "1")
   	@TableField(value = "is_del" ,select = false)
	private Integer isDel;

}
