package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Time;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Fri Dec 18 14:42:50 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName(value = "school_time")
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class SchoolTime {


    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * 时辰 上午AM 下午PM 晚上EV
     */
    @TableField(value = "whens")
    private String whens;

    /**
     * 上午或下午第几节课
     */
    @TableField(value = "several_lesson")
    private Long severalLesson;

    /**
     * 真实的第几节课
     */
    @TableField(value = "real_several_lesson")
    private Long realSeveralLesson;

    /**
     * 上课时间
     */
    @TableField(value = "school_time_start")
    private Time schoolTimeStart;

    /**
     * 下课时间
     */
    @TableField(value = "school_time_end")
    private Time schoolTimeEnd;

}
