package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import lombok.experimental.Accessors;


/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Dec 09 08:38:45 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName( value ="storage" )
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor()
@Accessors(chain = true)
@ApiModel
public class Storage  extends BaseEntity {



	@TableId(value = "id",type = IdType.AUTO)
	private Long id;

	/**
	 * 访问路径
	 */
	@ApiModelProperty(value = "访问路径")
   	@TableField(value = "access_url" )
	private String accessUrl;

	/**
	 * 存储类型
	 */
	@ApiModelProperty(value = "存储类型")
   	@TableField(value = "type" )
	private String type;

	public Storage(String accessUrl, String type) {
		this.accessUrl = accessUrl;
		this.type = type;
	}
}
