package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Dec 21 15:25:21 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName( value ="subject_school_time" )
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class SubjectSchoolTime {




   	@TableId(value = "id",type = IdType.AUTO)
	private Long id;

	/**
	 * 学科id
	 */
   	@TableField(value = "subject_id" )
	private Long subjectId;

	/**
	 * 星期几
	 */
   	@TableField(value = "week" )
	private Long week;

	/**
	 * 上课时间（需要在上课时间表去查真实时间）
	 */
   	@TableField(value = "school_time" )
	private String schoolTime;

}
