package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.commons.lang3.StringUtils;

import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Dec 17 21:49:39 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName( value ="subject" )
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Subject  implements Comparable<Subject>{




   	@TableId(value = "id",type = IdType.AUTO)
	private Long id;

	/**
	 * 班级id
	 */
   	@TableField(value = "grade_id" )
	private Long gradeId;

	/**
	 * 学科
	 */
   	@TableField(value = "subject" )
	private String subject;

   	@TableLogic(value = "0",delval = "1")
   	@TableField(value = "is_del" ,select = false)
	private Integer isDel;

	/**
	 * 是否过期(一学期的时间)
	 */
   	@TableField(value = "overdue_time" )
	private Date overdueTime;

	/**
	 * 创建人
	 */
   	@TableField(value = "create_by",fill = FieldFill.INSERT)
	private Long createBy;

	/**
	 * 创建时间
	 */
   	@TableField(value = "create_time",fill = FieldFill.INSERT)
	private Date createTime;


   	@TableField(exist = false)
	private Integer week;

   	@TableField(exist = false)
	private String schoolTime="";

	@Override
	public int compareTo(Subject o) {
		if(StringUtils.isBlank(o.getSchoolTime())){
			return -1;
		}
		return this.schoolTime.compareTo(o.getSchoolTime());
	}
}
