package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Dec 09 10:47:48 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName( value ="user_classgrade" )
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserClassgrade  {


   	@TableId(value = "id",type = IdType.AUTO)
	private Long id;

	/**
	 * 用户ID
	 */
   	@TableField(value = "user_id" )
	private Long userId;

	/**
	 * 班级ID
	 */
   	@TableField(value = "class_grade_id" )
	private Long classGradeId;

   	@TableField(value = "is_del" )
	private Integer isDel;

}
