package tech.ouyu.quickResponder.back.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Dec 17 21:49:44 CST 2020.</p>
 *
 * @author (ousakai)
 */

@Data
@TableName( value ="user_subject" )
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class UserSubject {




   	@TableId(value = "id",type = IdType.AUTO)
	private Long id;

	/**
	 * 学科id
	 */
   	@TableField(value = "subject_id" )
	private Long subjectId;

	/**
	 * 学生id
	 */
   	@TableField(value = "user_id" )
	private Long userId;

	/**
	 * 创建时间
	 */
   	@TableField(value = "create_time" ,fill = FieldFill.INSERT)
	private Date createTime;

}
