spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/quick?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
        enabled: true
        reset-enable: true
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
      initial-size: 1
      #验证连接有效与否的SQL，不同的数据配置不同
      validation-query: select 1
      min-idle: 1
      #最大在线链接
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 10000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #这里建议配置为TRUE，防止取到的连接不可用
      test-on-borrow: true
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #这里配置提交方式，默认就是TRUE，可以不用配置
      default-auto-commit: true
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
  redis:
    database: 0
#    password: alonepig
#    host: 10.4.68.42
    host: 127.0.0.1
    port: 6379
#    cluster:
#      nodes: 10.4.68.42:8001,10.4.68.42:8002,10.4.68.42:8003,10.4.68.42:8004,10.4.68.42:8005,10.4.68.42:8006

